import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Thanks for looking!
        </h1>

        <p className={styles.description}>
          My Products
        </p>

        <div className={styles.grid}>
          <a
            href=""
            className={styles.card}
            target="_blank" rel="noopener noreferrer"
          >
            <h2>whack-a-gopher &rarr;</h2>
            <p>Fun game to play whack-a-mole with cute characters.</p>
            {/* TODO: add skill tag: */}
          </a>

          <a href="https://github.com/yuu-sky20/actix-space-remover"
            className={styles.card}
            target="_blank" rel="noopener noreferrer"
          >
            <h2>actix-space-remover &rarr;</h2>
            <p>Remove superfluous line breaks and white space from text.</p>
          </a>

          <a
            href="https://github.com/yuu-sky20/slot-machine-app"
            className={styles.card}
            target="_blank" rel="noopener noreferrer"
          >
            <h2>slot-machine-app &rarr;</h2>
            <p>Experience a slot machine game.</p>
          </a>

          <a
            href="https://github.com/yuu-sky20/simple-web-piano"
            className={styles.card}
            target="_blank" rel="noopener noreferrer"
          >
            <h2>Simple Web Piano &rarr;</h2>
            <p>That can be played on the web.</p>
          </a>
        </div>

        <p className={styles.description}>
          Skills
        </p>

        <div>
          <section className={styles.grid_skill}>
            <h3 className={styles.description_skill}>Proficient :</h3>
            <div className={styles.grid_card_skill}>
              <p className={styles.card}>
                C
              </p>
              <p className={styles.card}>
                C++
              </p>
              <p className={styles.card}>
                Rust
              </p>
              <p className={styles.card}>
                Javascript (Typescript)
              </p>
            </div>
          </section>
          <section className={styles.grid_skill}>
            <h3 className={styles.description_skill}>Be usable : </h3>
            <div className={styles.grid_card_skill}>
              <p className={styles.card}>
                C#
              </p>
              <p className={styles.card}>
                Python
              </p>
              <p className={styles.card}>
                Haskell
              </p>
              <p className={styles.card}>
                Go
              </p>
              <p className={styles.card}>
                Docker
              </p>
              <p className={styles.card}>
                Git
              </p>
              <p className={styles.card}>
                React
              </p>
              <p className={styles.card}>
                Vue
              </p>
            </div>
          </section>
          <section className={styles.grid_skill}>
            <h3 className={styles.description_skill}>Touched it : </h3>
            <div className={styles.grid_card_skill}>
              <p className={styles.card}>
                Ruby
              </p>
              <p className={styles.card}>
                Java
              </p>
              <p className={styles.card}>
                Elm
              </p>
              <p className={styles.card}>
                Common Lisp
              </p>
              <p className={styles.card}>
                Kubernetes
              </p>
            </div>
          </section>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
